export const ImagesMapCardText = new Map()
.set('buster', "/images/np_txt_buster.png")
.set('quick', "/images/np_txt_quick.png")
.set('arts', "/images/np_txt_arts.png")
.set('extra', "/images/np_txt_extra.png")