export const ImagesMapCardText = new Map()
.set('buster', "https://apps.atlasacademy.io/db/assets/card_txt_buster.png")
.set('quick', "https://apps.atlasacademy.io/db/assets/card_icon_quick.png")
.set('arts', "https://apps.atlasacademy.io/db/assets/card_txt_arts.png")
.set('extra', "https://apps.atlasacademy.io/db/assets/card_txt_extra.png")